coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
        if_ci_failed: success
        informational: true
    patch:
      default:
        target: auto
        threshold: 0%
        base: auto
        if_ci_failed: success
        informational: true

comment: false

github_checks:
  annotations: true

ignore:
  - "noxfile.py"
