# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start with the official Python image that has poetry pre-installed
FROM python:3.10-slim as base

# Set environment variables
ENV POETRY_VERSION=1.1.13
ENV WECOM_WEBHOOK_URL="your WeCom bot webhook URL"

# Install poetry
RUN pip install poetry==$POETRY_VERSION

# Set the working directory
WORKDIR /app

# Copy the poetry lock file and pyproject.toml to the container
COPY pyproject.toml poetry.lock ./

# Install dependencies with poetry
RUN poetry install --no-dev

# Copy the rest of the application code to the container
COPY src/ src/

# Expose the necessary port (change this if needed)
EXPOSE 8000

# Run the server
ENTRYPOINT ["poetry", "run", "wecom-bot-mcp-server"]